# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'


# # Replace the '❯' symbol in the prompt with '➜'
# [character] # The name of the module we are configuring is 'character'
# success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
#
# # Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true
# Nordic-darker color palette
#2e3440	user
#3b4252	dir
#434c5e	git
#4c566a	version
#5e81ac	doc (from dracula color palette)
#6272a4	time (from dracula color palette)

# some extra symbols
# 
# 
#[░▒▓](#2e3440)\
# ---------------------------------------------------------------
format = """
$directory\
$git_branch\
$git_status\
$character\
"""

# $username\
# $cmd_duration\
# $time\
# $c\
# $python\
# $elixir\
# $elm\
# $golang\
# $haskell\
# $java\
# $julia\
# $nodejs\
# $nim\
# $rust\
# $scala\
# $docker_context\

 
add_newline = true # add new line between prompts

[line_break]
disabled = false

[username]
show_always = true
# style_user = "bg:#2e3440"
# style_root = "bg:#9A348E"
# format = '[\[$user\]:: ]($style)'
format = '[\[s\]: ]($style)'
disabled = false
# disabled = true

[os]
# style = "bg:#9A348E"
disabled = true # Disabled by default

[directory]
# style = "bg:#3b4252"
format = "[$path ]($style)"
truncation_length = 3 # or any larger number you prefer
truncate_to_repo = true
# truncation_symbol = ".../"
# fish_style_pwd_dir_length = 1  # Changes how paths are displayed

# [directory.substitutions]
# "Downloads" = " "
# "Music" = " "
# "Pictures" = " "

[git_branch]
symbol = ""
# style = "bg:#434c5e"
format = '[$symbol $branch ]($style)'


# [git_status]
# # style = "bg:#434c5e"
# format = '[$all_status$ahead_behind ]($style)'

[c]
symbol = " "
# style = "bg:#4c566a"
# format = '[[via](text) $symbol($version) ]($style)'
format = '[$symbol]($style)'

[python]
symbol = " "
# style = "bg:#4c566a"
# format = '[[via](text) $symbol($version) ]($style)'
format = 'via [(${virtualenv}) $symbol]($style)'


[docker_context]
symbol = " "
# style = "bg:#5e81ac"
# format = '[[via](text) $symbol($version) ]($style)'
format = '[$symbol]($style)'

[elixir]
symbol = " "
# style = "bg:#434c5e"
# format = '[[via](text) $symbol($version) ]($style)'
format = '[$symbol]($style)'

[elm]
symbol = " "
# style = "bg:#434c5e"
# format = '[[via](text) $symbol($version) ]($style)'
format = '[$symbol]($style)'

[golang]
symbol = " "
# style = "bg:#434c5e"
# format = '[[via](text) $symbol($version) ]($style)'
format = '[$symbol]($style)'

[haskell]
symbol = " "
# style = "bg:#434c5e"
# format = '[[via](text) $symbol($version) ]($style)'
format = '[$symbol]($style)'

[java]
symbol = " "
# style = "bg:#434c5e"
# format = '[[via](text) $symbol($version) ]($style)'
format = '[$symbol]($style)'

[julia]
symbol = " "
# style = "bg:#434c5e"
# format = '[[via](text) $symbol($version) ]($style)'
format = '[$symbol]($style)'

[nodejs]
symbol = " "
# style = "bg:#434c5e"
# format = '[[via](text) $symbol($version) ]($style)'
format = '[$symbol]($style)'

[rust]
symbol = "󱘗 "
# style = "bg:#434c5e"
# format = '[[via](text) $symbol($version) ]($style)'
format = '[$symbol]($style)'

[scala]
symbol = " "
# style = "bg:#434c5e"
# format = '[[via](text) $symbol($version) ]($style)'
format = '[$symbol]($style)'

[time]
disabled = true
use_12hr = true
# time_format = "%R" # Hour:Minute Format
# style = "bg:#6272a4"
format = '[ $time ]($style)'
	
[character]
# success_symbol = '[✦](green)'
success_symbol = '[✦](#6272a4)'
error_symbol = '[✦](red)'
# success_symbol = '[ λ](#6272a4)'
# error_symbol = '[ λ](red)'
# style = "bg:#6272a4"

[cmd_duration]
min_time = 500
format = '[$duration ](#6272a4)'
disabled = true
